language: ruby
rvm:

  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - ree
#   - jruby
#   - ruby-head
# env:
#   - SPHINX_BIN=/usr/local/sphinx-0.9.9/bin SPHINX_VERSION=0.9.9
#   - SPHINX_BIN=/usr/local/sphinx-1.10/bin SPHINX_VERSION=1.10
#   - SPHINX_BIN=/usr/local/sphinx-2.0.1/bin SPHINX_VERSION=2.0.1
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"